version: '3.9'
services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  library:
    build: .
    environment:
      - PORT=3000
      - REDIS_URL=redis://storage
    ports:
      - 80:3000
    depends_on:
      - storage
    